### ISSUE TITLE
Adição de empresa

### ISSUE THREAD

**Issue by shikow-laroye** [pythonbrasil/pyBusinesses-BR#102]
Olá, trabalho na empresa ZAP Imóveis(www.zapimoveis.com.br) e usamos Python no desenvolvimento dos nossos sistemas. Como faço para adicionar o ZAP na lista?

**Comment by Bernardoow** [comment]
@shikow 

Acredito que através de Pull Requests.

1. Faça o fork do repo para o seu github
2. Clone para seu computador
3. Edite o readme.md, adicionado sua empresa.
4. Faça o commit e o push para seu repositório
5. Crie uma pull request
6. Espere ser aceito a pr !!!
