### ISSUE TITLE
Oportunidade única: Desenvolvedor Python - ESSS

### ISSUE THREAD

**Issue by GP-ESSS** [pythonbrasil/pyBusinesses-BR#156]
Temos vagas na ilha da Magia, Florianópolis/SC para trabalhar na conceituada empresa Multinacional ESSS! 😍

A ESSS é uma multinacional brasileira sediada na cidade de Florianópolis/SC. Disponibilizamos ao mercado as mais avançadas ferramentas de CAE na área de fluidodinâmica, análise estrutural, eletromagnetismo e multifísica, além de customização e desenvolvimento de softwares sob medida de acordo com a necessidade de cada cliente. Estamos presentes no Brasil e no exterior, incluindo Argentina, Chile, Colômbia, Peru, México, Portugal, Espanha, França e Estados Unidos.

E para quem escolhe Florianópolis para viver, além de poder usufruir da melhor capital em qualidade de vida do país, famosa por suas praias, estará em um dos maiores polos de tecnologia do Brasil.

Não perca essa oportunidade! Se inscreva já: Desenvolvedor Python : https://esss.gupy.io/jobs/722617

**Comment by rougeth** [comment]
SPAM
