### ISSUE TITLE
Adicionar coluna para nome da cidade

### ISSUE THREAD

**Issue by claytonaalves** [pythonbrasil/pyBusinesses-BR#35]
Seria interessante redefinir o formato das tabelas para: Empresa, Cidade, Site, Contato.

**Comment by sergiomario** [comment]
Certo, daí os títulos seriam os Estados e as cidades apareceriam como um item da tabela. Certo?

**Comment by claytonaalves** [comment]
Exato.

**Comment by sergiomario** [comment]
Feito :+1:
